Create issue
Since I upgrade to the latest core my purifiers no longer work and the log is showing errors. Could this be related to the new naming convention? The purifiers are online (I can ping them) and have not been connected to the internet for nearly 2 years (separate VLAN, to avoid unwanted firmware "improvements").

I tried to install the repo of CumpsD as well as this has some updates but no luck - anyone else with these errors? @GeorgeSG , yours still operational or did you discontinue Philips airpurifiers altogether?

Logger: homeassistant.components.fan
Source: custom_components/philips_airpurifier_http/fan.py:120
Integration: Fan (documentation, issues)
First occurred: 15:58:46 (2 occurrences)
Last logged: 15:58:46

Error while setting up philips_airpurifier_http platform for fan
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 353, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/philips_airpurifier_http/fan.py", line 119, in async_setup_platform
    client = await hass.async_add_executor_job(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/philips_airpurifier_http/fan.py", line 120, in <lambda>
    lambda: HTTPAirClient(config[CONF_HOST], False)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pyairctrl/http_client.py", line 111, in __init__
    self.load_key()
  File "/usr/local/lib/python3.11/site-packages/pyairctrl/http_client.py", line 159, in load_key
    self._get_key()
  File "/usr/local/lib/python3.11/site-packages/pyairctrl/http_client.py", line 122, in _get_key
    with urllib.request.urlopen(req) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: